Id: Alison.GAtec
Name: GAtec
Publisher: GAtec
Version: 1.0.0
Channel: Stable
License: MIT
InstallerType: exe
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/alsnxz/Nardini/releases/download/v1.0.0/setupPt_Br.exe
    InstallerSha256: A337D77E9752122C13AF84AA2806DE29B0F43E157522D6CE9B8685CDBE5FDD16
    InstallerSwitches:
      Silent: /S
      SilentWithProgress: /S /progress